#!bin/bash
# -*- ENCODING: UTF-8 -*-

##------------------------------------------------------------------------------------------

## STAGE01 here you put routes to private keys, as is shown in the next example:

service1="/.ssh/gitlabKey"

#--------------------------------------------------------------------------------------------

## STAGE02 here you put the users (optional) for services as is shown in the next example:

userService1="John Doe";

##--------------------------------------------------------------------------------------------

## STAGE03 here you define the pendriveLocation and destinationInHome as is shown in the example:

pendriveLocation="/media/$USER/K-MSM-01";
destinationInHome="/home/$USER/.ssh/config";

##--------------------------------------------------------------------------------------------

## STAGE04 here you add more services if needed, mantaining the syntax as is shown with the first: 

routeToConfigService1=$pendriveLocation$service1;

##--------------------------------------------------------------------------------------------

## STAGE05 here you set the ssh client config file, add services as you need, following the example:
## TEMP-configPortable.txt is the temporal config file autogenerated. 

echo "Host github.com
    HostName github.com
    IdentityFile $routeToConfigService1
" > TEMP-configPortable.txt

##--------------------------------------------------------------------------------------------

## STAGE06 here you dont need to change anything

cp TEMP-configPortable.txt $destinationInHome 

rm -rf TEMP-configPortable.txt

exit

##--------------------------------------------------------------------------------------------